# -*- coding: utf-8 -*-
"""StatisticsPacket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E49Ghb1eF3CE9c5igWoaDfuvJdgcJYC-
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model 
pd.__version__

"""# Reading dataset
# Чтение набора данных
"""

import pandas 
df = pandas.read_csv("/content/HydroGeologyFull.csv",sep=';') 
#print(df.head(12))
df.columns

"""IGE – инженерно-геологический элемент, описание дано ниже
w, d.e. – природная влажность
e, d.e. – коэффициент пористости
E, Mpa – модуль деформации
f, o – угол внутреннего трения
C, kPa – удельное сцепление
p, g/cm3 – плотность 
ps, g/cm3 – плотность твердой компоненты
pd, g/cm3 – плотность скелета
Sr, d.e. – коэффициент водонасыщения



IGE - geotechnical element, description is given below
w, d.e. - natural moisture
e, d.e. - coefficient of porosity
E, Mpa - deformation modulus
f, o - angle of internal friction
C, kPa - specific adhesion
p, g / cm3 - density
ps, g / cm3 - solid component density
pd, g / cm3 - skeleton density
Sr, d.e. - coefficient of water saturation
"""

df

"""q* – лобовое сопротивление, МПа
Q* – боковое сопротивление, кН

Dependent variables: q and Q
Зависимые переменные: q и Q

"""

df.loc[0:740, ['q', 'Q']]

data = pd.read_csv('/content/HydroGeologyFull.csv',';')
data.isnull().any()

X = df[['ps','pd']]
Y = df['Q']

import matplotlib.pyplot as plt


plt.scatter(df['Q'],df['Sr'], color='green')
plt.title('Зависимые переменные Q и коэффициент водонасыщения', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='blue')
plt.ylabel('Sr', fontsize=16 , color='brown')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['Sr'], color='darkgrey')
plt.title('Зависимые переменные q и коэффициент водонасыщения', fontsize=14)
plt.xlabel('q', fontsize=16 , color='blue')
plt.ylabel('Sr', fontsize=16 , color='brown')
plt.grid(True)
plt.show()



plt.scatter(df['Q'],df['pd'], color='lightblue')
plt.title('Зависимые переменные Q и плотность скелета g/cm3', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='brown')
plt.ylabel('pd', fontsize=16 , color='darkblue')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['pd'], color='blue')
plt.title('Зависимые переменные q и плотность скелета g/cm3', fontsize=14)
plt.xlabel('q', fontsize=16 , color='grey')
plt.ylabel('pd', fontsize=16 , color='darkgreen')
plt.grid(True)
plt.show()

plt.scatter(df['Q'],df['ps'],color='lightgreen')
plt.title('Зависимые переменные Q и  плотность твердой компоненты g/cm3', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='brown')
plt.ylabel('ps', fontsize=16 , color='darkblue')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['ps'],color='red')
plt.title('Зависимые переменные q и  плотность твердой компоненты g/cm3', fontsize=14)
plt.xlabel('q', fontsize=16 , color='green')
plt.ylabel('ps', fontsize=16 , color='blue')
plt.grid(True)
plt.show()

plt.scatter(df['Q'],df['p'],color='cyan')
plt.title('Зависимые переменные Q и  плотность g/cm3', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='red')
plt.ylabel('p', fontsize=16 , color='green')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['p'],color='purple')
plt.title('Зависимые переменные  и  плотность g/cm3', fontsize=14)
plt.xlabel('q', fontsize=16 , color='cyan')
plt.ylabel('p', fontsize=16 , color='green')
plt.grid(True)
plt.show()

plt.scatter(df['Q'],df['f'],color='darkgreen')
plt.title('Зависимые переменные Q и угол внутреннего трения', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='purple')
plt.ylabel('f', fontsize=16 , color='red')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['f'],color='violet')
plt.title('Зависимые переменные Q и угол внутреннего трения', fontsize=14)
plt.xlabel('q', fontsize=16 , color='black')
plt.ylabel('f', fontsize=16 , color='red')
plt.grid(True)
plt.show()

plt.scatter(df['Q'],df['E'],color='lightgreen')
plt.title('Зависимые переменные Q и модуль деформации', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='black')
plt.ylabel('E', fontsize=16 , color='blue')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['E'],color='yellow')
plt.title('Зависимые переменные Q и модуль деформации', fontsize=14)
plt.xlabel('q', fontsize=16 , color='lightblue')
plt.ylabel('E', fontsize=16 , color='brown')
plt.grid(True)
plt.show()

plt.scatter(df['Q'],df['e'],color='lightgreen')
plt.title('Зависимые переменные Q и коэффициент пористости', fontsize=14)
plt.xlabel('Q', fontsize=16 , color='black')
plt.ylabel('e', fontsize=16 , color='blue')
plt.grid(True)
plt.show()

plt.scatter(df['q'],df['e'],color='grey')
plt.title('Зависимые переменные Q и коэффициент пористости', fontsize=14)
plt.xlabel('q', fontsize=16 , color='purple')
plt.ylabel('e', fontsize=16 , color='cyan')
plt.grid(True)
plt.show()